alias v="nvim"
alias update="sudo emerge --sync && sudo emerge -uDN @world"
alias clean="sudo eclean-dist && sudo eclean-dist -d && sudo eclean-pkg && sudo eclean-pkg -d"
alias weather="curl wttr.in"
alias sway="dbus-launch --exit-with-session sway -D noscanout"
#alias sway="dbus-run-session sway --unsupported-gpu -D noscanout"
alias reboot="loginctl reboot"
alias shutdown="loginctl poweroff"
